# -*- python -*-

# Draumr build system
#
# Copyright (c) Shikhin Sethi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os

Import("env")
our_env = Environment()

# Hide the ugly compiler command lines and display nice messages.
our_env["ASCOMSTR"] = "  AS    $SOURCE"
our_env["CCCOMSTR"] = "  CC    $SOURCE"
our_env["LINKCOMSTR"] = "  LINK  $TARGET"

CRC32 = our_env.Program("CRC32.util", "CRC32.c")

# Save the CRC32 target in the environment as we will need it later.
env["CRC32"] = CRC32

