# -*- python -*-

# Draumr build system
#
# Copyright (c) Shikhin Sethi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os

Import("env")
our_env = Environment()

colors = {}
colors['cyan']   = '\033[96m'
colors['purple'] = '\033[95m'
colors['blue']   = '\033[94m'
colors['green']  = '\033[92m'
colors['yellow'] = '\033[93m'
colors['red']    = '\033[91m'
colors['end']    = '\033[0m'


# Hide the ugly compiler command lines and display nice messages.
our_env["ASCOMSTR"] = "  %s[AS]%s    $SOURCE" % (colors['green'], colors['end'])
our_env["CCCOMSTR"] = "  %s[CC]%s    $SOURCE" % (colors['green'], colors['end'])
our_env["LINKCOMSTR"] = "  %s[LINK]%s  $TARGET" % (colors['green'], colors['end'])

CRC32 = our_env.Program("CRC32.util", "CRC32.c")
ToSIF = our_env.Program("ToSIF.util", "ToSIF.c")

Depends(CRC32, ToSIF)

# Save the CRC32 target in the environment as we will need it later.
env["CRC32"] = CRC32
env["ToSIF"] = ToSIF