# -*- python -*-

 # Draumr build system.
 #
 # Copyright (c) 2013, Shikhin Sethi
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
 #     * Redistributions of source code must retain the above copyright
 #       notice, this list of conditions and the following disclaimer.
 #     * Redistributions in binary form must reproduce the above copyright
 #       notice, this list of conditions and the following disclaimer in the
 #       documentation and/or other materials provided with the distribution.
 #     * Neither the name of Draumr nor the
 #       names of its contributors may be used to endorse or promote products
 #       derived from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 # ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 # WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 # DISCLAIMED. IN NO EVENT SHALL SHIKHIN SETHI BE LIABLE FOR ANY
 # DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 # (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 # LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 # ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import("Env")

Src = ["Src/Header.asm",
       "Src/Main.c",
       "Src/BIT.c",
       "Src/String.c",
       "Src/PMM.c",
       "Src/Debug.c",
       "Src/Abort.c",
       "Src/BootFiles.c",
       "Src/Output.c",
       "Src/FPU.asm",
       "Src/CPU.asm",
       "Src/Math.c",
       "Src/API.c"]

# An environment building the BAL binary.
# NOTE that this may be totally unneccessary, but I haven't figured out
# how do cleanly add some CCFLAGS options then remove them without screwing up.
# I'm probably being evil, but hey!
BALEnv = Env.Clone()
BALEnv.Append(CCFLAGS = ["-march=i586", "-m32"])
BAL = BALEnv.Program("BAL", [File for File in Src], LINKFLAGS = "-m elf_i386 -TSource/Boot/BAL/Link.ld", LIBS=['Bitmap'])

# Save the BAL target in the Environment as we will need it later.
Env["BAL"] = BAL
