# -*- python -*-

 # Draumr build system.
 #
 # Copyright (c) 2012, Shikhin Sethi
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
 #     * Redistributions of source code must retain the above copyright
 #       notice, this list of conditions and the following disclaimer.
 #     * Redistributions in binary form must reproduce the above copyright
 #       notice, this list of conditions and the following disclaimer in the
 #       documentation and/or other materials provided with the distribution.
 #     * Neither the name of the <organization> nor the
 #       names of its contributors may be used to endorse or promote products
 #       derived from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 # ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 # WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 # DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 # DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 # (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 # LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 # ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os

Import("env", "sys_env")

src = ["Src/Header.asm",
       "Src/Main.c",
       "Src/BIT.c",
       "Src/String.c",
       "Src/PMM.c",
       "Src/Log/Debug.c",
       "Src/Abort.c",
       "Src/BootFiles.c",
       "Src/Output.c",
       "Src/FPU.asm",
       "Src/Math.c",
       "Src/OutputMod/OutputMod.c",
       "Src/OutputMod/Blit.c",
       "Src/OutputMod/Blit8BPP.c",
       "Src/OutputMod/Blit15BPP.c",
       "Src/OutputMod/Blit16BPP.c",
       "Src/OutputMod/Blit24BPP.c",
       "Src/OutputMod/Blit32BPP.c",
       "Src/OutputMod/Serial.c",
       "Src/OutputMod/Enhance/Scale.c",
       "Src/OutputMod/Enhance/Dither.c" ]


# A target for building the DBAL binary.
DBAL = sys_env.Program("DBAL", [x for x in src], LINKFLAGS = "-m elf_i386 -TSource/System/Boot/DBAL/Link.ld", CCFLAGS = "-m32 -ISource/System/Boot/DBAL/Include/")

Depends(DBAL, src)

# Save the DBAL target in the environment as we will need it later.
env["DBAL"] = DBAL
