# -*- python -*-

# Draumr build system
#
# Copyright (c) Shikhin Sethi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os

Import("env", "sys_env")


src = ["Src/Header.asm",
       "Src/Main.c",
       "Src/BIT.c",
       "Src/String.c",
       "Src/PMM.c",
       "Src/Log/Debug.c",
       "Src/Abort.c",
       "Src/BootFiles.c",
       "Src/Output.c",
       "Src/FPU.asm",
       "Src/Math.c",
       "Src/OutputMod/OutputMod.c",
       "Src/OutputMod/Blit.c",
       "Src/OutputMod/Blit8BPP.c",
       "Src/OutputMod/Blit15BPP.c",
       "Src/OutputMod/Blit16BPP.c",
       "Src/OutputMod/Serial.c",
       "Src/OutputMod/Enhance/Scale.c",
       "Src/OutputMod/Enhance/Dither.c" ]


# A target for building the DBAL binary.
DBAL = sys_env.Program("DBAL", [x for x in src], LINKFLAGS = "-m elf_i386 -TSource/System/Boot/DBAL/Link.ld", CCFLAGS = "-m32 -ISource/System/Boot/DBAL/Include/")

Depends(DBAL, src)

# Save the DBAL target in the environment as we will need it later.
env["DBAL"] = DBAL
