# -*- python -*-

# Draumr build system
#
# Copyright (c) Shikhin Sethi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os

Import("env", "sys_env")

src = ["Link.ld",
       "Format/Format.inc",
       "Src/Main.asm",
       "Src/A20.asm",
       "Src/Memory.asm",
       "Src/Video/Video.asm"]

# A target for building the Stage 1 binary.
BIOSobj = sys_env.Object("BIOS", "Src/Main.asm", LINKFLAGS = "-m elf_i386 -TSource/System/Boot/BIOS/BIOS/Link.ld")
BIOS = sys_env.Program("BIOS", "BIOS", LINKFLAGS = "-m elf_i386 -TSource/System/Boot/BIOS/BIOS/Link.ld")

Depends(BIOSobj, src)
Depends(BIOS, BIOSobj)

env["BIOS"] = BIOS

Depends(env["BIOS"], env["CRC32"])
